Sign up form
ThaiHoang-newbie/Food_store_website pull request #4
Opened 2023-04-02 03:14 UTC by ThaiHoang-newbie

Fix bug: Wrong message when not registered yet and delete admin folder

2023-04-02 08:35 UTC, cuonghuunguyen commented on Sign_up/login.php
> +  <style id="INLINE_PEN_STYLESHEET_ID">
move css to a separated file

2023-04-02 08:42 UTC, cuonghuunguyen requested changes

2023-04-02 08:42 UTC, cuonghuunguyen commented on Sign_up/login.php
> +            $select_log_user_email = "SELECT `email` FROM `user` WHERE `email` = '$email_input'";
use [prepared statement](https://www.w3schools.com/php/php_mysql_prepared_statements.asp) to prevent SQL injection
https://viblo.asia/p/sql-injection-MgNeWWbKeYx

2023-04-02 08:42 UTC, cuonghuunguyen commented on Sign_up/forgot_pass.php
> +<?php
what is this file? why do u add this file

2023-04-02 08:42 UTC, cuonghuunguyen commented on Sign_up/verify_pass.php
> +        * {
move this to a separated file, its too long here

2023-04-02 08:58 UTC, cuonghuunguyen commented
I cannot find the mailing code.

2023-04-02 08:58 UTC, cuonghuunguyen requested changes

2023-04-02 08:58 UTC, cuonghuunguyen commented on Sign_up/login.php
> +    function show_hide_password(target) {
you have duplicated this code

2023-04-02 08:58 UTC, cuonghuunguyen commented on Sign_up/sign_up.php
> +    <div id="svgWrapper">
This code is not readable, you can move the sgv to a separated file or just remove it

2023-04-02 10:10 UTC, cuonghuunguyen commented on Sign_up/login.php
> +                header("Location: http://localhost/Food_store_website/");
why don't you store the user information into the session?

2023-04-06 14:54 UTC, cuonghuunguyen approved these changes

2023-04-08 08:04 UTC, closed without merging

2023-04-08 08:05 UTC, ThaiHoang-newbie commented
I merged the one with update infor branch